#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S4,     Compass,        sensorI2CHiTechnicCompass)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#define JOY_SCALE 0.78	//scales down the values from the algorithm for getting motor values from the joystick because otherwise they are too large - is equal to 100 / 128 because 128 is the highest value the joystick has
#define JOY_THRESHOLD 30		//threshold for when joystick value is considered zero, because there is a good amount of noise in the joysticks
task main()
{
InitialDirection = SensorValue(compass);
	while(true)
			{
				int Correction = SensorValue(Compass) - InitialDiretion;
				int moveX = cos(correction)
				int moveY = sin(correction)
		motor[omniFR] = TELE_OP_SCALE * JOY_SCALE * (moveX - moveY);
		motor[omniBR] = TELE_OP_SCALE * JOY_SCALE * (-moveX - moveY);
		motor[omniFL] = TELE_OP_SCALE * JOY_SCALE * (moveX + moveY);
		motor[omniBL] = TELE_OP_SCALE * JOY_SCALE * (-moveX + moveY);
	}
}
