#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     comp,           sensorI2CHiTechnicCompass)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     color,          sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     omniBL,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     omniBR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     omniFL,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     omniFR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     liftL,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     liftR,         tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    rotFL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rotFR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    rotBR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    rotBL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    armBase,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    armClaw,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int compass = 0;

int getVariance(int record, int newAngle)
{
	if (abs(record - newAngle) > 180)
		return 360 - abs(record - newAngle);

	return record - newAngle;
}

task main()
{
	int tick = 0, offset = 0;
	wait10Msec(10);
	compass = SensorValue[compass];

	while (true)
	{
		offset = SensorValue[compass] - comp; tick++;
		nxtDisplayCenteredTextLine(1, "Start = %d", comp);
		nxtDisplayCenteredTextLine(2, "Compass: %d", SensorValue[compass]);
		nxtDisplayCenteredTextLine(3, "New Vary: %d", getVariance(compass, SensorValue[compass]));
		nxtDisplayCenteredTextLine(4, "IR = %d", SensorValue[ir]);
		nxtDisplayCenteredTextLine(5, "Color = %d", SensorValue[color]);
	  wait10Msec(31);
	}
}
