#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     comp,           sensorI2CHiTechnicCompass)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     color,          sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     omniBR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     omniFR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     omniBL,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     omniFL,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     nomotorhere,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    rotFL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rotFR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    rotBR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    rotBL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    armClaw,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define JOY_SCALE 0.78	//scales down the values from the algorithm for getting motor values from the joystick because otherwise they are too large - is equal to 100 / 128 because 128 is the highest value the joystick has
#define JOY_THRESHOLD 30		//threshold for when joystick value is considered zero, because there is a good amount of noise in the joysticks
#define SQR(val) (val) * (val) // square function
#define JOY_NOISE 12 // Accounts for joystick noise
#define TC_Lim 5 //How fast joystick changes rotation. Lower means faster.

#define rotatespeed 5 //The higher this number is, the slower corrections to the direction happen.


task main()
{
	wait10Msec(50);
	float targetangle; //the angle to which we want the robot to turn
	float correction;
	float speed;
	float targetcounter;
	float theta;
	float rotatechange; //the higher this number, the slower the effects from the joystick take place.
	targetangle = SensorValue(comp); //baseline direction, number out of 360.

	while(true)
	{

	getJoystickSettings(joystick); //update joystick position

			// Check for noise
		if ((sqrt(SQR(joystick.joy1_x1) + SQR(joystick.joy1_y1)) < JOY_THRESHOLD))
		{
			speed = 0;
		}
		else speed = (sqrt(SQR(joystick.joy1_x1) + SQR(joystick.joy1_y1)))/127; //set speed


		// Drive teleop



		if (abs(joystick.joy1_x2) > JOY_NOISE) // Check for noise
		{
			targetcounter ++;
		}
		if (targetcounter > TC_Lim)
			{
				targetangle =+ joystick.joy1_x2/rotatechange;
			}
		correction = ((SensorValue[comp] - targetangle)/(rotatespeed * 360));

		if (correction < JOY_NOISE)
			{

				correction = 0;
			}
		speed = (speed -= correction);

		if (joystick.joy1_x1 == 0)
			{
				theta = joystick.joy1_y1 > 0 ? PI/2 : PI * 3/2; //Oron wrote this. It is neater so we will keep it, but my way on the next line is still cool.
				 //theta = (PI + ((PI/2) * (joystick.joy1_y1/abs(joystick.joy1_y1)))) - (PI/4); //because theta is undefined when joystick.joy1_x1 is 0 and I don't know how the nxt will handle it
			}
		else
			{
				theta = (atan((joystick.joy1_y1)/(joystick.joy1_x1)))/* - (PI/4))*/; //I don't know if we need the pi/4 yet. We will test both ways.
			}
		// Set the motors
		motor[omniFR] = (speed * sin(theta)) + correction;
		motor[omniBR] = (speed * cos(theta)) + correction;
		motor[omniFL] = (speed * -cos(theta)) + correction;
		motor[omniBL] = (speed * -sin(theta)) + correction;
		wait10Msec(5);
	}
}
