#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     comp,           sensorI2CHiTechnicCompass)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     color,          sensorCOLORFULL)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     omniBL,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     omniBR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     omniFL,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     omniFR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     liftL,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     liftR,         tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    rotFL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rotFR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    rotBR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    rotBL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    armBase,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    armClaw,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Global Driving Variables
int UserAngle = 0;
int CompassBase = 0;
#define VARIANCE_NOISE 2

int A_C_REGTILT = 0;
int A_B_REGTILT = 0;

// Values of wheel servos
#define OMNI 127 // Servo value of omniwheels
#define FL_CAR 0
#define FR_CAR 255 // Servo value of wheels in car mode
#define BL_CAR 255
#define BR_CAR 0

// Sets all the motors to the specified number
void SetSpin ( int degrees )
{
	motor[omniFL] = degrees;
	motor[omniFR] = degrees;
	motor[omniBL] = degrees;
	motor[omniBR] = degrees;
}

// Sets the wheels from one mode to the other.
void SetWheels(bool goCarMode, bool applyMotors = true)
{
	if (goCarMode)
	{
		servo[rotFL] = FL_CAR;
		servo[rotFR] = FR_CAR;
		servo[rotBL] = BL_CAR;
		servo[rotBR] = BR_CAR;

		if (applyMotors)
		{
			wait10Msec(16);
			SetSpin(-15);
			wait10Msec(40);
			SetSpin(0);
		}
	}
	else // set motors to auto no mouse mode
	{
		servo[rotFL] = OMNI;
		servo[rotFR] = OMNI;
		servo[rotBL] = OMNI;
		servo[rotBR] = OMNI;

		if (applyMotors)
		{
			wait10Msec(16);
			SetSpin(+15);
			wait10Msec(40);
			SetSpin(0);
		}
	}
}

void SetMoveCompass ( int turn )
{
	int variance = SensorValue[comp] - CompassBase + (turn * 0.1);
	if (variance > VARIANCE_NOISE || variance < -VARIANCE_NOISE)
	{
		motor[omniFL] -= variance;
		motor[omniFR] += variance;

		motor[omniBL] -= variance;
		motor[omniBR] -= variance;
	}

}

void SetMoveMath ( int turn, int power)
{
	float newPower = power * 0.71 * 0.8;

	int mathy = degreesToRadians(turn);

	int x = sin(mathy);
	int y = cos(mathy);


	motor[omniFR] = newPower * (x - y);
	motor[omniBR] = newPower * (-x - y);
	motor[omniFL] = newPower * (x + y);
	motor[omniBL] = newPower * (-x + y);
}

void SetMathCompass ( int turn, int pwr )
{
	int offset = CompassBase - SensorValue[comp];
	SetMoveMath(turn + offset, pwr);
}
