#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     comp,           sensorI2CHiTechnicCompass)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     color,          sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     omniBR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     omniFR,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     omniBL,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     omniFL,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     lift,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     nomotorhere,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    rotFL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rotFR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    rotBR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    rotBL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    armClaw,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define SQR(x) ((x) * (x))
task main()
{
	int speed;
	float direction;
while(true)
{
		servo[rotFL] = 127;
		servo[rotFR] = 127;
		servo[rotBL] = 127;
		servo[rotBR] = 127;

	getJoystickSettings(joystick);
	speed = sqrt(SQR(joystick.joy1_x1) + SQR(joystick.joy1_y1));
	if (joystick.joy1_x1 == 0)
	{
		direction = (PI/2) * (abs(joystick.joy1_y1)/(joystick.joy1_y1));
	}
	else
	{
	direction = atan((joystick.joy1_y1/128)/(joystick.joy1_x1/128)) * (abs(joystick.joy1_y1)/(joystick.joy1_y1));
	}

	motor[omniBR] = (speed * cos(direction - (PI/4)));
	motor[omniFR] = (speed * sin(direction - (PI/4)));
	motor[omniBL] = (speed * sin(direction - (PI/4)));
	motor[omniFL] = (speed * cos(direction - (PI/4)));
}
}
