#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     HTPB,                sensorI2CCustom9V)
#pragma config(Sensor, S3,     SMUX_1,              sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX_2,              sensorI2CCustom)
#pragma config(Motor,  motorA,          a,             tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          b,             tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          c,             tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     fr,            tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     br,            tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     fl,            tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     bl,            tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     xlifta,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     xliftb,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************************************************\
*                                                                                                                                                                                                                                                                           *
* PROGRAM: TeleOp program for Get Over It 2010-2011                               *
* VERSION: 2.0                                                                                                                                                                                                              *
* PURPOSE: Controllable user program for Tele-operational period.     *
Omni-bot must be configured according to the diagram on    *
the OMNI-driver.c file                                     *
* AUTHOR: Team R.A.B.B.I.                                             *
* DATE:          April 2011                                                                                                                                                                               *
*                                                                                                                                                                                                                                                                                 *
* LICENSE: GNU GPL V3 2011                                            *
\**********************************************************************/



/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef COMPLETEDRIVER
#include "drivers/CompleteDriver.h"
#endif

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
int speed;

task clamp{
  servo[servo3] = 12;
  servo[servo4] = 255-12;
  while (true){
    if (joy2Btn(2) == 1){
      servo[servo3] = 29;
      servo[servo4] = 255-29;
    }
    if (joy2Btn(4) == 1){
      servo[servo3] = 12;
      servo[servo4] = 255-12;
    }
    wait1Msec(50);
  }
}

void initializeRobot(){
  wait1Msec(50);
  HTMAGstartCal(MAGPOS);
  speed = 100;    // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  StartTask(sensorRead);
  bDisplayDiagnostics = true;
  kalmindebugdisplay = false;
  eraseDisplay();
  startkalmin();
  wait1Msec(50);
  speed = 100;
  StartTask(Jdrive);
  nMotorEncoder[xlifta] = 0;
  nMotorEncoder[xliftb] = 0;
  StartTask(clamp);
}


task main(){
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase
  while (true){
    getJoystickSettings(joystick);
    if (joy1Btn(7) == 1 && joy1Btn(8) == 1){
      stopmot();
      resetkalmin();
      wait1Msec(4);}
    if (joy1Btn(7) ==1){
      speed=40;}
    if (joy1Btn(8) ==1){
      speed=20;}
    if (joy1Btn(7) ==0 && joy1Btn(8) ==0){
      speed=100;}
    if (joy1Btn(9) == 1){
      findgyrooffset();
    }
    if (joy1Btn(10) == 1){
      undisturb = true;
    }
    else{
      undisturb = false;
    }
    getjoystickts();
    if (joystick.joy1_TopHat == 0){      // If the topmost button on joy1's D-Pad ('TopHat') is pressed:
      forward(15);
    }
    else if (joystick.joy1_TopHat == 2){
      right(17);
    }
    else if (joystick.joy1_TopHat == 4){
      backward(17);
    }
    else if (joystick.joy1_TopHat == 6){
      left(17);
    }
    else {drive(speed);}


    //if ((nMotorEncoder[xlifta] > XLIFTLOW && joystick.joy2_y1 < 0) || (nMotorEncoder[xlifta] < XLIFTHIGH && joystick.joy2_y1 > 0) || joystick.joy2_y1 == 0){
    if (joy2Btn(7) ==1){
      motor[xlifta] = -80;
      motor[xliftb] = -80;
    }
    else if (joy2Btn(8) == 1){
      motor[xlifta] = 80;
      motor[xliftb] = 80;
    }
    else{
      motor[xlifta] = -joystick.joy2_y1/1.2;
      motor[xliftb] = -joystick.joy2_y2/1.2;
    }
    //}
    if (joy2Btn(6) == 1){
      motor[a] = 100;
      motor[b] = 100;
      motor[c] = 100;
    }
    else{
      motor[a] = 0;
      motor[b] = 0;
      motor[c] = 0;
    }
    if (joy2Btn(5) == 1){
      motor[a] = -100;
      motor[b] = -100;
      motor[c] = -100;
    }
    if (joy2Btn(3) == 1){
      servo[servo5] = 85;
    }
    else{
      servo[servo5] = 255;
    }
    if (joy2Btn(1)){
      servo[servo1] = 255;
    }
    else{
      servo[servo1] = 80;
    }
    if (MagnetReading() > MAGTHREASHOLD){
      StartTask(magnetdetect);
    }
    EndTimeSlice();
    wait1Msec(20);
  }
}
