#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     BR,            tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FR,            tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     BlockatorTL,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     PullBottom,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     BL,            tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     FL,            tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     BlockatorTR,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    PullTop,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    BlockDrop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    BlockatorBL,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    BlockatorBR,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_5,    none5,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    none6,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////
// Utilities for Hutzbots Code //
////////////////////////////////
// Containing driving utility
// functions for the Hutzbots robot.
////////////////////////////////////


//////////////////////////////////////////////////
//                 Compass
//////////////////////////////////////////////////
float quarterPI = PI / 4;

void Stop()
{
	motor[FL] = motor[FR] = motor[BL] = motor[BR] = 0;
}

//////////////////////////////////////////////////
//                 Driving
//////////////////////////////////////////////////
void driveRobot(float speed, float theta, float factor = 0, int rotate = 0)
{
	motor[FL] = motor[BR] = round(speed * sin(theta - quarterPI) * factor + (rotate * factor));
	motor[FR] = motor[BL] = round(speed * cos(theta - quarterPI) * factor + (rotate * factor));
}

void driveMeccanum(float speed, float theta, float factor = 0, int rotate = 0)
{
	motor[FL] = round(speed * -sin(theta + quarterPI) * factor - (rotate * factor));
	motor[BR] = round(speed * -sin(theta + quarterPI) * factor + (rotate * factor));
	motor[FR] = round(speed * +cos(theta + quarterPI) * factor + (rotate * factor));
	motor[BL] = round(speed * +cos(theta + quarterPI) * factor - (rotate * factor));
}

int sqr(int input)
{ return input * input; }
