#pragma config(Sensor, S1,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          Turny,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
while(true)
{
	if(sensorvalue[IR] == 5)
	{
		motor[motorB] = 0;
	}
	else
	{
	if(sensorvalue[IR] < 5)
	{
	motor[motorB] = -10;
	}
	else
	{
		motor[motorB] = 10;
	}
	}
}



}
