#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     conte,          sensorNone)
#pragma config(Sensor, S3,     colur,          sensorI2CHiTechnicColor)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S2_C1_1,     BR,            tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     FR,            tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     BL,            tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     FL,            tmotorTetrix, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////////////////////////////////////////////
//														 Hutzbots Mecanum Wheel Testing Code																//
//																																																//
//																							A																									//
//																						 / \																								//
//																						/		\																								//
//																			<----+-----+---->																					//
//																			 \	/				\	 /																					//
//																				\/Hutzbots!\/																						//
//																				/\				 /\																						//
//																			 /	\				/	 \																					//
//																			<----+-----+---->																					//
//																						\		/																								//
//																						 \ /																								//
//																							V																									//
//																																																//
//																																																//
////////////////////////////////////////////////////////////////////////////////////////////////////
/*


This code aims to map each wheel to a different joystick. Only the Y values are used.
This program is meant to assist in the understanding of how different wheels need to be
powered to move in a given direction.

Put the Joy1 joystick in front of the Joy2 joystick on a table.


*/
//												Controlling our robot with a joystick and stuff.
////////////////////////////////////////////////////////////////////////////////////////////////////
// Alex Tagieri (math/music), Joshua Hailman (form, appearance, comments, design), Hodaya (Mathymath)
////////////////////////////////////////////////////////////////////////////////////////////////////
#include "JoystickDriver.c"

#define noise 10
#define scale 0.78


task main()
{
	int move;
	while(true)
	{
		getJoystickSettings(joystick);
		if(joystick.joy1_y1 < noise && joystick.joy1_y2 < noise && joystick.joy2_y1 < noise && joystick.joy2_y2 < noise)
		{
			move = 0;
		}
		else
		{
			move = 1;
		}

		motor[FL] = move * scale * (joystick.joy1_y1);
		motor[FR] = move * scale * (joystick.joy1_y2);
		motor[BL] = move * scale * (joystick.joy2_y1);
		motor[BR] = move * scale * (joystick.joy2_y2);


	}
}

//Because documentation is for people less important than me.
