#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     conte,          sensorI2CMuxController)
#pragma config(Sensor, S3,     colur,          sensorI2CHiTechnicColor)
#pragma config(Motor,  mtr_S2_C1_1,     BR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     FR,            tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     BL,            tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     FL,            tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_SCALE 0.77
// How far off the joystick can be
#define JOY_NOISE 12

float quarterPI = PI / 4;
float theta, speed; // Vector math to the wheel
float rotate;

void driveMeccanum(float speed, float theta, float rotate)
{
	motor[FL] = round(speed * sin(theta + quarterPI)) - rotate;
	motor[BR] = round(speed * sin(theta + quarterPI)) + rotate;
	motor[FR] = round(speed * -cos(theta + quarterPI)) + rotate;
	motor[BL] = round(speed * -cos(theta + quarterPI)) - rotate;
}

int sqr (int input)
{ return input * input; }

task main()
{
	while(1==1)
	{
		getJoystickSettings(joystick);

		speed = sqrt(sqr(joystick.joy1_x1) + sqr(joystick.joy1_y1));

		if (speed > JOY_NOISE)
		{
			theta = atan2(joystick.joy1_y1, joystick.joy1_x1);
		}
		else
		{
			speed = 0;
			theta = 0;
		}
			if (abs(joystick.joy1_x2) > JOY_NOISE)
		{
			rotate = joystick.joy1_x2 * JOY_SCALE;
		}
		else // No rotation is detected
		{
			rotate = 0;
		}

		driveMeccanum(speed, theta, rotate);
	}
}























// At the beginning:
time1[T1] = 0;

// How many miliseconds
int time = time1[T1];

switch (time1[T1])
{
	case 1:123651234569877+++/*-147258361147258369+
	147258396014725836901472583690147258360147258369014725369147285396

	*/
	// code
	break;

	case 2:
	// code
	break;
}
string input = "hi";
switch (input)
{
	case "off":
	case "exit":
	case "goaway":
	// code
	break;
}
