#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     BR,            tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FR,            tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Amry,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Flaggy,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     BL,            tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     FL,            tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    Latch,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    BlockDrop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setMotor(tMotor motorName)
{
	motor[motorName] = 100;
	Sleep(140);
	motor[motorName] = 0;
	Sleep(200);
}
void initEncode(tMotor motorName, int rotate)
{
	motor[motorName] = 0;
	nMotorEncoderTarget[motorName] = rotate;
	motor[motorName] = 20;
}

task main()
{
		//initEncode(FL, 720);

		//while (nMotorRunState[FL] != runStateIdle) { }

	//	motor[FL] = 0;


	//for (int i = 0; i < 8; i++)
	//{
		//setMotor(i);
	//}

	//Sleep(1900);


	setMotor(FL);
	setMotor(FR);
	setMotor(BR);
	setMotor(BL);
	/*
	wait1Msec(800);

	setMotor(Flaggy);
	setMotor(Amry);*/

}
