#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FrontLD,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FrontRD,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     BackLD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BackRD,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define SCALE 128
#define THRESH 15

int ax;
int ay;
int bx;
int by;

task main()
{
	while(true)
	{
	getJoystickSettings(joystick);

	joystick.joy1_x1 = ax;
	joystick.joy1_y1 = ay;
	joystick.joy1_x2 = bx;
	joystick.joy1_y2 = by;

	motor[FrontLD] = ay - ax - bx;
	motor[FrontRD] = ay + ax + bx;
	motor[BackLD] = ay + ax - bx;
	motor[BackRD] = ay - ax + bx;
	}

}
