#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          motor1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motor2,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor3,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorRD,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorLD,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorT,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define THRESH 18
#define MINI 25
#define SCALE .78125


task main()
{
	while(true)
	{
		getJoystickSettings(joystick);


		if (joy1Btn(09))  // turns the crank
		{
			motor[motorG] = 100 ;
		}
		else
		{
			motor[motorG] = 0;
		}


		if (joy1Btn(06))  // runs the grabber inwards
		{
			motor[motorT] = -100;
		}
		else if (joy1Btn(6))  // runs the grabber outwards
		{
			motor[motorT] = 100;
		}
		else
		{
			motor[motorT] =0;
		}



		if (joy1Btn(4)) // the next four if and else if
	 {
	   motor[motorLD] = -MINI ;
	   motor[motorRD]= MINI ;
	 }

	  else if (joy1Btn(2))
	 {
	   motor[motorLD] = MINI ;
	   motor[motorRD] = -MINI ;
	 }

	  else if (joy1Btn(1))
	 {
	   motor[motorLD] = MINI ;
	   motor[motorRD] = MINI ;
	 }

	  else if (joy1Btn(3))
	 {
	   motor [motorLD] = -MINI ;
	   motor [motorRD] = -MINI ;
	 }

	 else
		{

		if ((joystick.joy1_y1) > THRESH || (joystick.joy1_y1) < -THRESH)
			{
				motor[motorLD]= ((-joystick.joy1_y1)* SCALE);
			}
		else {
			motor[motorLD]= 0;
					}


		if ((joystick.joy1_y2) > THRESH || (joystick.joy1_y2) < -THRESH)
			{
				motor[motorRD]= ((joystick.joy1_y2)* SCALE);
			}
		else {
				motor[motorRD]= 0;
					}

		}

		if (joy1Btn(5))
		{
			motor [motorLL] = 75;
			motor [motorRL] = 75;
		}
		else {
			motor [motorLL] = 0;
			motor [motorRL] = 0;
					}

		if (joy1Btn(7))
		{
			motor [motorLL] = -75;
			motor [motorRL] = -75;
		}
		else {
			motor [motorLL] = 0;
			motor [motorRL] = 0;
					}
	}
}
