#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     blockLift,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     wheelRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     omniRight,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     wheelLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     omniLeft,      tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    collectorRight,       tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    collectorTiltRight,   tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    dispenserTiltFront,   tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_5,    dispenserTiltBack,    tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_6,    dispenserTop,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_1,    collectorLeft,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    collectorTiltLeft,    tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Title: Tele-Op Main
Author: Oron Propp
Date: 11.13.2013
Company: The Pluralists

Motors:
omniRight
omniLeft
wheelRight
wheelLeft
blockLift

Servos:
collectorLeft
collectorRight
collectorTiltLeft
collectorTiltRight
dispenserTop
dispenserTiltFront
dispenserTiltBack
*/

#define MTR_MAX 100
#define MTR_MIN 0
#define MTR_DEBUG_TIME_MS 2000
#define MTR_DEBUG_TIME_SHORT_MS 1000
#define LIFT_MTR_PWR 50
#define SERVO_MAX 256
#define SERVO_MIN 0
#define MTR_THLD 10

#define BTN_LIFT_UP 1
#define BTN_COLLECT 2
#define BTN_LIFT_DOWN 3
#define BTN_COLLECT_TILT 4
#define BTN_DISPENSE_TOP 5
#define BTN_DISPENSE_TILT 6

#define NXT_DISPLAY_CTR_LINE 4

#define SERVO_LEFT_COLLECT_OPEN_POS 0
#define SERVO_LEFT_COLLECT_CLOSE_POS 256
#define SERVO_RIGHT_COLLECT_OPEN_POS 0
#define SERVO_RIGHT_COLLECT_CLOSE_POS 256

#define SERVO_LEFT_COLLECT_TILT_UP_POS 256
#define SERVO_LEFT_COLLECT_TILT_DOWN_POS 80
#define SERVO_RIGHT_COLLECT_TILT_UP_POS (SERVO_MAX - SERVO_LEFT_COLLECT_TILT_UP_POS)
#define SERVO_RIGHT_COLLECT_TILT_DOWN_POS (SERVO_MAX - SERVO_LEFT_COLLECT_TILT_DOWN_POS)

#define SERVO_DISPENSE_TOP_OPEN_POS 100
#define SERVO_DISPENSE_TOP_CLOSE_POS 0

#define SERVO_FRONT_DISPENSE_TILT_OPEN_POS 256
#define SERVO_FRONT_DISPENSE_TILT_CLOSE_POS 0
#define SERVO_BACK_DISPENSE_TILT_OPEN_POS (SERVO_MAX - SERVO_FRONT_DISPENSE_TILT_OPEN_POS)
#define SERVO_BACK_DISPENSE_TILT_CLOSE_POS (SERVO_MAX - SERVO_FRONT_DISPENSE_TILT_CLOSE_POS)

#define SERVO_STATE_NULL 0

#define BUTTON_MAX 50

#include "JoystickDriver.c"

bool collectServoState = SERVO_STATE_NULL;
bool collectTiltServoState = SERVO_STATE_NULL;
bool dispenseTopServoState = SERVO_STATE_NULL;
bool dispenseTiltServoState = SERVO_STATE_NULL;

int collectorButtonSet = 0;
int collectorTiltButtonSet = 0;

void teleOpInit() {
	motor[omniRight] = MTR_MIN;
	motor[omniLeft] = MTR_MIN;
	motor[wheelRight] = MTR_MIN;
	motor[wheelLeft] = MTR_MIN;
	motor[blockLift] = MTR_MIN;

	servo[collectorLeft] = SERVO_LEFT_COLLECT_CLOSE_POS;
	servo[collectorRight] = SERVO_RIGHT_COLLECT_CLOSE_POS;
	servo[collectorTiltLeft] = SERVO_LEFT_COLLECT_TILT_DOWN_POS;
	servo[collectorTiltRight] = SERVO_RIGHT_COLLECT_TILT_DOWN_POS;
	servo[dispenserTop] = SERVO_DISPENSE_TOP_CLOSE_POS;
	servo[dispenserTiltFront] = SERVO_FRONT_DISPENSE_TILT_CLOSE_POS;
	servo[dispenserTiltBack] = SERVO_BACK_DISPENSE_TILT_CLOSE_POS;
}

void debugDriveMotors() {

	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "omniRight");
	motor[omniRight] = MTR_MAX;
	wait1Msec(MTR_DEBUG_TIME_MS);
	motor[omniRight] = MTR_MIN;

	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "omniLeft");
	motor[omniLeft] = MTR_MAX;
	wait1Msec(MTR_DEBUG_TIME_MS);
	motor[omniLeft] = MTR_MIN;

	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "wheelRight");
	motor[wheelRight] = MTR_MAX;
	wait1Msec(MTR_DEBUG_TIME_MS);
	motor[wheelRight] = MTR_MIN;

	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "wheelLeft");
	motor[wheelLeft] = MTR_MAX;
	wait1Msec(MTR_DEBUG_TIME_MS);
	motor[wheelLeft] = MTR_MIN;
}

void updateDriveMotors() {

	int joy1Y = joystick.joy1_y1;
	int joy1X = joystick.joy1_x2;

	if(joy1Y < MTR_THLD && joy1Y > -MTR_THLD)
		joy1Y = 0;
	if(joy1X < MTR_THLD && joy1X > -MTR_THLD)
		joy1X = 0;

	motor[omniRight] = joy1Y-joy1X;
	motor[omniLeft] = -joy1Y-joy1X;
	motor[wheelRight] = joy1Y - joy1X;
	motor[wheelLeft] = -joy1Y - joy1X;
}

void debugBlockLiftMotor() {
	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "blockLift");
	motor[blockLift] = MTR_MAX;
	wait1Msec(MTR_DEBUG_TIME_SHORT_MS);
	motor[blockLift]=-MTR_MAX;
	wait1Msec(MTR_DEBUG_TIME_SHORT_MS);
	motor[blockLift] = MTR_MIN;
}

void updateBlockLiftMotor() {
	if (joy1Btn(BTN_LIFT_UP)) {
		motor[blockLift] = LIFT_MTR_PWR;
	} else if (joy1Btn(BTN_LIFT_DOWN)) {
		motor[blockLift] = -LIFT_MTR_PWR;
	} else {
		motor[blockLift] = MTR_MIN;
	}
}

void debugCollectorServos() {
	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "collectorRight");
	servo[collectorRight] = SERVO_RIGHT_COLLECT_OPEN_POS;
	wait1Msec(MTR_DEBUG_TIME_MS);
	servo[collectorLeft] = SERVO_LEFT_COLLECT_OPEN_POS;
	wait1Msec(MTR_DEBUG_TIME_MS);



	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "collectorLeft");
	servo[collectorRight] = SERVO_RIGHT_COLLECT_CLOSE_POS;
	wait1Msec(MTR_DEBUG_TIME_MS);
	servo[collectorLeft] = SERVO_LEFT_COLLECT_CLOSE_POS;
	wait1Msec(MTR_DEBUG_TIME_MS);
	}

void updateCollectorServos() {
	if (joy1Btn(BTN_COLLECT)) {
		if (collectorButtonSet < BUTTON_MAX) {
			collectorButtonSet++;
		} else {
		collectorButtonSet = 0;
		if (collectServoState == SERVO_STATE_NULL) {
			servo[collectorRight] = SERVO_RIGHT_COLLECT_OPEN_POS;
			servo[collectorLeft] = SERVO_LEFT_COLLECT_OPEN_POS;
		} else {
			servo[collectorRight] = SERVO_RIGHT_COLLECT_CLOSE_POS;
			servo[collectorLeft] = SERVO_LEFT_COLLECT_CLOSE_POS;
		}
		collectServoState = !collectServoState;
	}
	}
}

void debugCollectorTiltServos() {
	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "collectorTiltLeft/Right");
	wait1Msec(MTR_DEBUG_TIME_MS);
	servo[collectorTiltRight] = SERVO_RIGHT_COLLECT_TILT_UP_POS;
	servo[collectorTiltLeft] = SERVO_LEFT_COLLECT_TILT_UP_POS;
	wait1Msec(MTR_DEBUG_TIME_MS);
	servo[collectorTiltRight] = SERVO_RIGHT_COLLECT_TILT_DOWN_POS;
	servo[collectorTiltLeft] = SERVO_LEFT_COLLECT_TILT_DOWN_POS;
	wait1Msec(MTR_DEBUG_TIME_MS);
}

void updateCollectorTiltServos() {
	if (joy1Btn(BTN_COLLECT_TILT)) {
		if (collectorTiltButtonSet < BUTTON_MAX) {
			collectorTiltButtonSet++;
		} else {
		collectorTiltButtonSet = 0;
		if (collectTiltServoState == SERVO_STATE_NULL) {
			servo[collectorTiltRight] = SERVO_RIGHT_COLLECT_TILT_UP_POS;
			servo[collectorTiltLeft] = SERVO_LEFT_COLLECT_TILT_UP_POS;
		} else {
			servo[collectorTiltRight] = SERVO_RIGHT_COLLECT_TILT_DOWN_POS;
			servo[collectorTiltLeft] = SERVO_LEFT_COLLECT_TILT_DOWN_POS;
		}
		collectTiltServoState = !collectTiltServoState;
	}
	}
}

void debugDispenserServos() {
	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "dispenserTop");
	servo[dispenserTop] = SERVO_DISPENSE_TOP_OPEN_POS;
	wait1Msec(MTR_DEBUG_TIME_MS);
	servo[dispenserTop] = SERVO_DISPENSE_TOP_CLOSE_POS;

	nxtDisplayCenteredBigTextLine(NXT_DISPLAY_CTR_LINE, "dispenserTiltLeft/Right");
	servo[dispenserTiltFront] = SERVO_FRONT_DISPENSE_TILT_OPEN_POS;
	servo[dispenserTiltBack] = SERVO_BACK_DISPENSE_TILT_OPEN_POS;
	wait1Msec(MTR_DEBUG_TIME_MS);
	servo[dispenserTiltFront] = SERVO_FRONT_DISPENSE_TILT_CLOSE_POS;
	servo[dispenserTiltBack] = SERVO_BACK_DISPENSE_TILT_CLOSE_POS;
}

void updateDispenserServos() {
	if (joy1Btn(BTN_DISPENSE_TOP)) {
		if (dispenseTopServoState == SERVO_STATE_NULL) {
			servo[dispenserTop] = SERVO_DISPENSE_TOP_OPEN_POS;
		} else {
			servo[dispenserTop] = SERVO_DISPENSE_TOP_CLOSE_POS;
		}
		dispenseTopServoState = !dispenseTopServoState;
	}
	if (joy1Btn(BTN_DISPENSE_TILT)) {
		if (dispenseTiltServoState == SERVO_STATE_NULL) {
			servo[dispenserTiltFront] = SERVO_BACK_DISPENSE_TILT_OPEN_POS;
			servo[dispenserTiltBack] = SERVO_FRONT_DISPENSE_TILT_OPEN_POS;
		} else {
			servo[dispenserTiltFront] = SERVO_BACK_DISPENSE_TILT_CLOSE_POS;
			servo[dispenserTiltBack] = SERVO_FRONT_DISPENSE_TILT_CLOSE_POS;
		}
		dispenseTiltServoState = !dispenseTiltServoState;
	}
}

task main() {
	//debugDriveMotors();
	//debugBlockLiftMotor();
	//return;
	//teleOpInit();
	//waitForStart();
	//eraseDisplay();
	while (true) {
		getJoystickSettings(joystick);
		updateDriveMotors();
		updateBlockLiftMotor();
		updateCollectorServos();
		updateCollectorTiltServos();
		//updateDispenserServos();
	}
}
