#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Grabb,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Flag,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#define Conversion 100/128
#define joy_noise 10
task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if ((abs(joystick.joy1_y1) > joy_noise) || abs(joystick.joy1_y2) > joy_noise)
		{
			motor[Left] = joystick.joy1_y1 * Conversion;
			motor[Right] = joystick.joy1_y2 * Conversion;
		}
		if (joy1Btn(8) == 1)
		{
			motor[Flag] = 100;
		}
		else if (joy1Btn(6))
			motor[Flag] = -100;
		else
			motor[Flag] = 0;
		if (joy1Btn(2))
			motor[Grabb] = 100;
		else if (joy1Btn(4))
			motor[Grabb] = -100;
		else
			motor[Grabb] = 0;
	}
}
