#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Light,          sensorCOLORFULL)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Forklift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     BR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     Block,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    LScoop,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RScoop,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define Joy_Noise 8
#define Joy_Multiplier 100/181
task main()
{
	float m;
	float n;
	float p;

	while(true)
	{
		getJoystickSettings(joystick);
		int y = joystick.joy1_y1;
		int x = joystick.joy1_x1;
		//driving//
		if (((abs(x))>Joy_Noise)||((abs(y))>Joy_Noise))
		{
			int angle = atan(y/x)+45;
			int rotate;
			if ((abs(joystick.joy1_x2))>Joy_Noise)
			{
				rotate = joystick.joy1_x2;
			}
			else
			{
				rotate = 0;
			}
			if (joy1Btn(8) != 0)
			{
				m = (float) 1.0/2.0;
			}
			else
			{
				m = 1;
			}
			//.25 speed//
			if (joy1Btn(7) != 0)
			{
				n = (float) 1.0/4.0;
			}
			else
			{
				n = 1;
			}
			//x3 speed. Only to be used with 7 or with 7&8 together//
			if (joy1Btn(6) != 0)
			{
				p = 3;
			}
			else
			{
				p = 1;
			}
			//speed control//
			float speed = sqrt((pow(x,2)) + (pow(y,2)))*m*n*p*Joy_Multiplier;
			if((x>=0)&&(y>0))
			{
				motor [FL] = cosDegrees(angle)*speed - rotate;
				motor [FR] = sinDegrees(angle)*speed + rotate;
				motor [BR] = cosDegrees(angle)*speed + rotate;
				motor [BL] = sinDegrees(angle)*speed - rotate;
			}
			else if ((x>0)&&(y<=0))
			{
				motor [FL] = cosDegrees(angle)*speed - rotate;
				motor [FR] = -sinDegrees(angle)*speed + rotate;
				motor [BR] = cosDegrees(angle)*speed + rotate;
				motor [BL] = -sinDegrees(angle)*speed - rotate;
			}
			else if ((x<0)&&(y>=0))
			{
				motor [FL] = -cosDegrees(angle)*speed - rotate;
				motor [FR] = sinDegrees(angle)*speed + rotate;
				motor [BR] = -cosDegrees(angle)*speed + rotate;
				motor [BL] = sinDegrees(angle)*speed - rotate;
			}
			else if((x<=0)&&(y<0))
			{
				motor [FL] = -cosDegrees(angle)*speed - rotate;
				motor [FR] = -sinDegrees(angle)*speed + rotate;
				motor [BR] = -cosDegrees(angle)*speed + rotate;
				motor [BL] = -sinDegrees(angle)*speed - rotate;
			}
			else
			{
				motor [FL] = 0;
				motor [FR] = 0;
				motor [BR] = 0;
				motor [BL] = 0;
			}

			if(joy2Btn(4))
			{
				motor [Block] = 100;
			}
			else
			{
				motor[Block] = 0;
			}
			if (joy2Btn(8))
			{
				motor [Forklift] = 100;
			}
			else
			{
				motor[Forklift] = 0;
			}

			if (joy2Btn(3))
			{
				servo [LScoop] = 100;
				servo [RScoop] = -100;
			}
			else if (joy2Btn(2))
			{
				servo [LScoop] = 0;
				servo [RScoop] = 0;
			}
			if (joy2Btn(7))
			{
				motor [Flag] = 100;
			}
			else
			{
				motor[Flag] = 0;
			}
		}
	}
}
