#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Light,          sensorLightActive)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Forklift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_1,     Block,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    LScoop,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    RScoop,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	time1[T1] = 0;
	float TimeDriven = time1[T1];
	//Lift block in air//
	while (TimeDriven<2000)
	{
		motor[Forklift] = 100;
	}
	//f until light sensor detects colored line
	while (SensorValue(Light) != 80)
	{
		motor [FL] = 100;
		motor [FR] = 100;
		motor [BR] = 100;
		motor [BL] = 100;
	}
	wait1Msec(500);
	time1[T1] = 0;
	while (TimeDriven<1000)
	{
		motor [FL] = 100;
		motor [BL] = 100;
		motor [BR] = -100;
		motor [FR] = -100; //DONT CHANGE THESE 100's
	}
	while ((SensorValue(IR))>5 || (SensorValue(IR))<4)
	{
		//move right//
		motor [FL] = -100;
		motor [BL] = 100;
		motor [BR] = 100;
		motor [FR] = -100;
		getSensorRawADValue(IR);
	}
	wait1Msec(500);
	time1[T1] = 0;
	//execute drop blocks
	while (TimeDriven<1000)
	{
		motor [FL] = 100;
		motor [BL] = 100;
		motor [BR] = 100;
		motor [FR] = 100;
	}
	servo [LScoop] = -180;
	servo [RScoop] = 180;
	wait1Msec(1000);
	servo [LScoop] = 0;
	servo [RScoop] = 0;
	//drive right, drive forward, drive left//
	time1[T1] = 0;
	while (TimeDriven<1000)
	{
		motor [FR] = -100;
		motor [BR] = 100;
		motor [BL] = -100;
		motor [FL] = 100;
	}
	wait1Msec(1000);
	time1[T1] = 0;
	while (TimeDriven<1000)
	{
		motor [FL] = 100;
		motor [FR] = 100;
		motor [BR] = 100;
		motor [BL] = 100;
	}
	wait1Msec(1000);
	time1[T1] = 0;
	while (TimeDriven<1000)
	{
		motor [FR] = 100;
		motor [BR] = -100;
		motor [BL] = 100;
		motor [FL] = -100;
	}
	wait1Msec(1000);
	motor [FR] = 0;
	motor [FL] = 0;
	motor [BL] = 0;
	motor [BR] = 0;

}
