#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     BR,            tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FR,            tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     BlockMoteL,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Pullup,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     BL,            tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     FL,            tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     BlockMoteR,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    Latch,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    BlockDrop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    BlockServeL,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    BlockServeR,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "Youtilities.c"
#include "JoystickDriver.c"
#define LIFT_SPEED 10
#define JOY_SCALE 0.77
#define JOY_NOISE 10
#define LIGHT_THRESHOLD 17
#define BUTTON_MAX 50
float DrivingScale = 1; // The scale of the robot for driving
int Rotate; // How much to rotate the robot.
float theta, speed; // Vector math to the wheel

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if (joy1Btn(5) && joy1Btn(7))
			DrivingScale = 1.3;

		else if (joy1Btn(5))
			DrivingScale = .5;

		else if (joy1Btn(7))
			DrivingScale = .25;

		else // Neither button pressed
			DrivingScale = 1;


		speed = sqrt(sqr(joystick.joy1_x1) + sqr(joystick.joy1_y1));

		if (speed > JOY_NOISE)
		{
			theta = atan2(joystick.joy1_y1, 	joystick.joy1_x1);
		}
		else // The joystick values are small enough to fail
		{
			theta = 0; speed = 0;
		}
		if (abs(joystick.joy1_x2) > JOY_NOISE)
		{
			Rotate = joystick.joy1_x2;
		}
		else // No rotation is detected
		{
			Rotate = 0;
		}
		driveMeccanum(speed, theta, DrivingScale, Rotate);

		if (joy2Btn(2))
		{
			servo[Latch] = 255; // Full speed ahead!
		}
		else if (joy2Btn(4))
		{
			servo[Latch] = 0; // Woah there. Back it up!
		}
		else
		{
			servo[Latch] = 127;
		}
		if (joy1Btn(5))
		{
			motor[BlockMoteL] = motor[BlockMoteR] = 25;
		}
		else if (joy1Btn(7))
		{
			motor[BlockMoteL] = motor[BlockMoteR] = -25;
		}
		else
		{
			motor[BlockMoteL] = motor[BlockMoteR] = 0
			;
		}

		/*if (abs(joystick.joy2_y2) > JOY_NOISE)
		{
			motor[BlockMoteL] = motor[BlockMoteR] = .3 * JOY_SCALE * joystick.joy2_y2;
		}
		else
		{
			motor[BlockMoteL] = motor[BlockMoteR] = 0;
		*/
		if (joy2Btn(5))
		{
			motor[Flag] = 100;
		}
		else if (joy2Btn(7))
		{
			motor[Flag] = -100;
		}
		else motor[Flag] = 0;

		if (joy2Btn(6))
		{
			motor[Pullup] = 100;
		}
		else if (joy2Btn(8))
		{
			motor[Pullup] = -100;
		}
		else
		{
			motor[Pullup] = 0;
		}

		if (joy1Btn(1))
		{
			servo[BlockServeL] = servo[BlockServeR] = 5;
		}
		else if (joy1Btn(3))
		{
			servo[BlockServeL] = servo[BlockServeR] = 250;
		}
		else
		{
			servo[BlockServeL] = servo[BlockServeR] = 127;
		}

		if (joy2Btn(5))
		{
			motor[Flag] = 100;
		}
		else if (joy2Btn(7))
		{
			motor[Flag] = -100;
		}
		else
		{
			motor[Flag] = 0;
		}
	}
}
