#pragma config(Hubs,	S4, HTMotor,	HTMotor,	none,			none)
#pragma config(Sensor, S1,		 IR,						 sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,		 Compass,				 sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,		 ,							 sensorI2CMuxController)
#pragma config(Motor,	 motorA,					 ,						 tmotorNXT, openLoop)
#pragma config(Motor,	 motorB,					 ,						 tmotorNXT, openLoop)
#pragma config(Motor,	 motorC,					 ,						 tmotorNXT, openLoop)
#pragma config(Motor,	 mtr_S4_C1_1,			omniFR,				 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S4_C1_2,			omniFL,				 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S4_C2_1,			omniBL,				 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S4_C2_2,			omniBR,				 tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

//////////////////////////////////////////////////////////////////////////////////////////////////////
//																		 Includes Files
//////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"

//////////////////////////////////////////////////////////////////////////////////////////////////////
//																		 #Definitions
//////////////////////////////////////////////////////////////////////////////////////////////////////

#define SQR(x) ((x) * (x)) // Because ROBOTC needs a squaring operator/command

// # Joystick Values
#define JOY_SCALE 0.78 // Scales down motor values from joystick: 128 -> 100
#define JOY_NOISE 12 // Accounts for joystick noise

// # Arm Servo Values
#define A_SHAKE_AMPLITUDE_T 3 // How far the servo will rotate back and forth when in shake mode
#define A_C_CONTROLTILT 7 // how far the arm will rotate when the button is pressed
#define A_C_REGTILT 127 // the default value of the servo

// # Button Counter Values
#define BUTTON_TIMER 65 // for not looping the button commands





#define DrivingScale 1
#define JOY_SCALE 1
/*************************************************/

//////////////////////////////////////////////////////////////////////////////////////////////////////
//																	 Variables and cButtonCounter s
//////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	int rotate;
	int MoveX;
	int MoveY;

while(true)
{


			getJoystickSettings(joystick);
		if (abs(joystick.joy1_x2) > JOY_NOISE) // Check for noise
		{
			rotate = -joystick.joy1_x2 * JOY_SCALE;
		}

		else rotate = 0;

		if (sqrt(SQR(joystick.joy1_x1) + SQR(joystick.joy1_y1)) > JOY_NOISE) // Check for noise
		{
			/* Set driving values */
			MoveY = -joystick.joy1_x1;
			MoveX = -joystick.joy1_y1;
		}
		else // Values are too small
		{
			MoveX = 0;
			MoveY = 0;
		}

		{
			/*
			if (Filtered && MoveX > 0)
			{
				// Possible use reference method
				ufRotateAngle = atan((MoveY/127)/(MoveX/127));
				ufSpeed = sqrt(SQR(MoveX) + SQR(MoveY));

				SetMoveMath(ufRotateAngle + UserAngle, ufSpeed, rotate);
			}*/

			motor[omniFL] = round(DrivingScale * (JOY_SCALE * (+MoveX + MoveY) + rotate));
			motor[omniFR] = round(DrivingScale * (JOY_SCALE * (+MoveX - MoveY) + rotate));
			motor[omniBL] = round(DrivingScale * (JOY_SCALE * (-MoveX + MoveY) + rotate));
			motor[omniBR] = round(DrivingScale * (JOY_SCALE * (-MoveX - MoveY) + rotate));
		}
		}
}

		///////////////////////////////////////////////////
		//						 Button: OmniSwitch
		///////////////////////////////////////////////////
		//	 Switch the robot from omnimode to tankmode
		///////////////////////////////////////////////////
 // task main
